### PR TITLE
Type Error related fixes

### PR DESCRIPTION
**Pull request by rotexdegba**
* Added code to guard against some type errors in **\Ginfo\OS\Windows**

### CODE REVIEW

**Comment by Gemorroj** [comment]
@rotexdegba can you explain how to reproduce the problems?
I always have `FileSystem` and `LastBootUpTime`.

**Comment by rotexdegba** [comment]
> @rotexdegba can you explain how to reproduce the problems?
> I always have `FileSystem` and `LastBootUpTime`.

I am running on Windows 10 with all errors, warnings and notices turned on in PHP. I think it might have been before I ran **Set-ExecutionPolicy -ExecutionPolicy** .  

The **->setType($volume['FileSystem'] )** was blowing up for my dvd drive as it contained null and **setType** was expecting a string.

The other checks are defensive and don't adversely affect **Ginfo\OS\Windows** .

**Comment by Gemorroj** [comment]
@rotexdegba can you check master branch which last changes? i don't have dvd drive to check it myself.

**Comment by rotexdegba** [comment]
> @rotexdegba can you check master branch which last changes? i don't have dvd drive to check it myself.

Here's one error I am currently getting on windows with the latest master branch code, that would have been prevented by one of the changes in this pull request:

```
PHP Fatal error:  Uncaught Error: Call to a member function getTimestamp() on boolean in D:\SoftwareProjects\general-php-project\vendor\gemorroj\ginfo\src\OS\Windows.php:171
Stack trace:
#0 D:\SoftwareProjects\general-php-project\vendor\gemorroj\ginfo\src\Info.php(41): Ginfo\OS\Windows->getUptime()
```

**Comment by Gemorroj** [comment]
I can't reproduce the problem. Can you execute the powershell code and show me the result?
```powershell
Get-WmiObject -Class Win32_OperatingSystem LastBootUpTime
```

**Comment by rotexdegba** [comment]
> I can't reproduce the problem. Can you execute the powershell code and show me the result?
> 
> ```powershell
> Get-WmiObject -Class Win32_OperatingSystem LastBootUpTime
> ```

```
PS D:\SoftwareProjects\linux-server-info-api> Get-WmiObject -Class Win32_OperatingSystem LastBootUpTime


__GENUS          : 2
__CLASS          : Win32_OperatingSystem
__SUPERCLASS     :
__DYNASTY        :
__RELPATH        : Win32_OperatingSystem=@
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         :
__NAMESPACE      :
__PATH           :
LastBootUpTime   : 20200611194021.696016-360
PSComputerName   :
```

**Comment by Gemorroj** [comment]
Thanks a lot! I got it. That's problem with negative offset.

**Pull request closed without merging**
